

class Listing:
    def __init__(self,
                 listing_title,
                 listing_description,
                 listing_id,
                 listing_offerType,
                 listing_deleted,
                 listing_deletedAt,
                 listing_categories,
                 listing_availableFrom,
                 listing_createdAt,
                 listing_updatedAt,
                 listing_address_street,
                 listing_address_country,
                 listing_address_postalCode,
                 listing_address_locality,
                 listing_address_region,
                 listing_geo_x,
                 listing_geo_y,
                 listing_price_rent_gross,
                 listing_prices_extra,
                 listing_prices_net,
                 listing_price_rent_interval,
                 listing_price_buy_gross,
                 listing_currency,
                 listing_characteristics_hasParking,
                 listing_characteristics_lotSize,
                 listing_characteristics_hasBalcony,
                 listing_numberOfRooms,
                 listing_yearBuilt,
                 listing_yearLastRenovated,
                 listing_livingSpace,
                 listing_isChildFriendly,
                 listing_floor,
                 listing_prices_area,
                 listing_img_urls,

                 lister_name,
                 lister_website,
                 lister_phone,
                 lister_id,
                 lister_type,
                 lister_address):

        self.listing_title = listing_title,
        self.listing_description = listing_description,
        self.listing_id = listing_id,
        self.listing_offerType = listing_offerType,
        self.listing_deleted = listing_deleted,
        self.listing_deletedAt = listing_deletedAt,
        self.listing_categories = listing_categories,
        self.listing_availableFrom = listing_availableFrom,
        self.listing_createdAt = listing_createdAt,
        self.listing_updatedAt = listing_updatedAt,
        self.listing_address_street = listing_address_street,
        self.listing_address_country = listing_address_country,
        self.listing_address_postalCode = listing_address_postalCode,
        self.listing_address_locality = listing_address_locality,
        self.listing_address_region = listing_address_region,
        self.listing_geo_x = listing_geo_x,
        self.listing_geo_y = listing_geo_y,
        self.listing_price_rent_gross = listing_price_rent_gross,
        self.listing_prices_extra = listing_prices_extra,
        self.listing_prices_net = listing_prices_net,
        self.listing_price_rent_interval = listing_price_rent_interval,
        self.listing_price_buy_gross = listing_price_buy_gross,
        self.listing_currency = listing_currency,
        self.listing_characteristics_hasParking = listing_characteristics_hasParking,
        self.listing_characteristics_lotSize = listing_characteristics_lotSize,
        self.listing_characteristics_hasBalcony = listing_characteristics_hasBalcony,
        self.listing_numberOfRooms = listing_numberOfRooms,
        self.listing_yearBuilt = listing_yearBuilt,
        self.listing_yearLastRenovated = listing_yearLastRenovated,
        self.listing_livingSpace = listing_livingSpace,
        self.listing_isChildFriendly = listing_isChildFriendly,
        self.listing_floor = listing_floor,
        self.listing_prices_area = listing_prices_area,
        self.listing_img_url = listing_img_urls,

        self.lister_name = lister_name,
        self.lister_website = lister_website,
        self.lister_phone = lister_phone,
        self.lister_id = lister_id,
        self.lister_type = lister_type,
        self.lister_address = lister_address
